---
abstract: 'collectd plugin for reading queue metrics from rsyslog/imstats logfile'
author:
  - 'Markus Benning <ich@markusbenning.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Collectd-Plugins-RsyslogStats
requires:
  Collectd: 0
  File::ReadBackwards: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Collectd-Plugins-RsyslogStats
  repository: https://github.com/benningm/Collectd-Plugins-RsyslogStats
version: 1.001
